---

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    init: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./certs:/etc/traefik/certs:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./logs:/var/log/traefik
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-dashboard.entrypoints: web
      traefik.http.routers.traefik-dashboard.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik-dashboard.service: api@internal

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.whoami-http.entrypoints: web
      traefik.http.routers.whoami-http.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami-https.entrypoints: websecure
      traefik.http.routers.whoami-https.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami-https.tls: true

networks:
  traefik:
    external: true
