---

name: ShellCheck CI
'on':
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sniff errors with shellcheck
        run: ./entrypoint.sh lint_shell
